//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba5._2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int Review_ID { get; set; }
        public int User_ID { get; set; }
        public int Product_ID { get; set; }
        public string Review_Text { get; set; }
        public int Rating { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
